version: '3.5'

services:
  frontend:
    build: .
    restart: always
    container_name: buscapets-frontend
    volumes:
      - ./src:/usr/buscapets/src
      - ./.env:/usr/buscapets/.env
    ports:
      - '5173:5173'
    command: sh -c 'yarn dev'
